### PR TITLE
Create Design_a_linked_list

### PR DESCRIPTION
**Pull request by Ganesh-Agarwal-25**
This PR is for hacktober fest 2020.

### CODE REVIEW

**Comment by Ganesh-Agarwal-25** [comment]
@ayushagarwal28  This PR is for hacktober 2020, please review.

**Comment by Ganesh-Agarwal-25** [comment]
@bamsarts @vzsky This PR is for hacktober 2020, please review.

**Review by vzsky — COMMENTED** [review]
I don't know why they mentioned me, but as I read through, I didn't find any major issue here. 
Just thinking that addAtHead and addAtTail could be simple rewrite calling the addAtIndex function.

```
void addAtTail(int val) {
     addAtIndex(getLength(head), val)
}
```

**Comment by Ganesh-Agarwal-25** [comment]
@vzsky can you please merge it for hacktober 2020.

**Comment by vzsky** [comment]
No!!! I'm not the one responsible for this.
I can't merge.
wait for @IEEE-IIITSricity to review.

**Comment by Ganesh-Agarwal-25** [comment]
@vzsky  okay thanks!

**Pull request merged**
